language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: etPOhDAwHO7hPXkqHJFkQtNgAPyBy54MzzosHP5goQj6ZifJj9dLWqceiSA+ImXRoiQzr4k/OhKw1VtXt1D3EbhT4qek/cw1K1jzrlPbgzFxUlxWX6HWNr+GEpI6PAjU+wpPXYjQOQRsb51BKSz7RbXN5fbqhhBIzkWC63YtL1gsfjM9GZuY0qmbFpNCWIMxl7T7mvbYTmiOX67LjGdFGukBOnCLrq/VBf9vffGH+S8xE0KPpN5HuLZ70mEil7YQatvwJOrWnYb9rLur9HyF/4QSQH1q688+AXT02s7VCa/ZGIna/D9JlPO27P2snUp/6JDj9FOlw4ZJMi0c3J2ClUKOdD0H4oTOwnAlh6vbNV6F8XUX2WR8kpXxna8Cf4y4zU7edz1MOy0nDHkfH3rwD6HyGySuIQSrHlm9stCxjh325yUibZh/04v/PYv319k9Zaw/WuPl9Z4mYZ7UkBcdxD3Ilzyq0J+xRtaWlmh2dv9j3gF720WRLu7K+catfmXFRriaFP+o2JsgtLmQ9sAbW3G7ePdlovnhXbhhqdJDNGHrNWy7M0UbjHOpxQ0r1bBTzVbukduwZ8IZ5PmdIQIkbS4JocWHK+3892bmLb5gsf+uwXk+/aKp35n1sLsK1Klv8YCR9exkXuzInQbEcFlRTtLfw4vD6FtIr87byBDu0R4=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: wMyiR5AJkYati0vgSg6mF/H+oly0OGqjVUNBV9ttPlQanwN6Yp6ldJFtFwNCfELXvNw2M0Ci8kjFSBq7SuIFO3ZHZJim8QjDAn07BnlDXrAoWgpVp9Pu6cEWlW1hhIak7aEJsKiok736Fj34aN9QkcE1cWbYstZ22WFwzb8ztqKAQ4AMN0nGOv8Xmw+Pb38uBuVZ7hLEMtC85L8imExeCiqp0YiDnPtY8AoY/W1bfSlznC3Nn3AO0mBbyJMaDTsFirlzoeMsRa9qOHrWFHa1pCQvDS/FejQSfh9N4LTDXpdi2R6vkvi8OKtrUTgEaU2hwUNRVXPFgpn01aAV0zW3ce9qX9PaRseTkHDkj5OxZTv5YA+k4FUaXEff4Z6Grn9qxYOqeBgwHRcywhdgeouzk0j7p9W0dd5nPJ7NB3YhbjTjuVmPYR+4quHg1eoj9cw/VbN94+3bHydK8sNcuoKCeTas38HDt0e3ADAUyK8Q3r2z3R9AdUw5XjRuy4CzCNOiUxblWH++Ilw/+kObp14IzWX54hhv69kJnlxD0iApcVdwTm6637HHTpMzV7PL5oU9fykkQxH1v7/oqmw7dtpymmeI5Q9EdnQgJl/ijghTJ1ObDHjs5Xma7N3Rl9R3uB383QI40LHc8++ovOF8WdMabLLIqVRaE2e75V51HdIz/Bo=
sudo: false
